stages:
  - test
  - verify
  - deploy

image: gradle:7.3.3-jdk17

variables:
  SONAR_TOKEN: $SONAR_TOKEN
  GRADLE_USER_HOME: ".cache/gradle/"

cache:
  paths:
    - .cache

test:
  stage: test
  script:
    - gradle test

push-image:
  stage: deploy
  script:
    - gradle build
      -Dquarkus.container-image.push=true
      -Dquarkus.container-image.image=${CI_REGISTRY_IMAGE}:staging:test
      -Dquarkus.container-image.username=${CI_REGISTRY_USER}
      -Dquarkus.container-image.password=${CI_REGISTRY_PASSWORD}

sonarqube:
  stage: verify
  variables:
    GIT_DEPTH: 0
  script: gradle sonarqube -Dsonar.qualitygate.wait=true
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH' 
