stages:
  - build

image: docker:20.10.13

build:
  stage: build
  script:
    - apk add openjdk17
    - ./gradlew build
      -Dquarkus.container-image.build=true
      -Dquarkus.container-image.push=true
      -Dquarkus.container-image.image=${CI_REGISTRY_IMAGE}
      -Dquarkus.container-image.username=${CI_REGISTRY_USER}
      -Dquarkus.container-image.password=${CI_REGISTRY_PASSWORD}