stages:
  - build

image: gradle:jdk17

build:
  stage: build
  script:
    - gradle build
      -Dquarkus.container-image.push=true
      -Dquarkus.container-image.image=${CI_REGISTRY_IMAGE}
      -Dquarkus.container-image.username=${CI_REGISTRY_USER}
      -Dquarkus.container-image.password=${CI_REGISTRY_PASSWORD}