stages:
  - test
  - verify
  - deploy

image: gradle:7.3.3-jdk17

variables:
  SONAR_TOKEN: $SONAR_TOKEN
  GRADLE_USER_HOME: ".cache/gradle/"

test:
  stage: test
  script:
    - gradle test
  cache:
    key: gradle
    paths:
      - .cache/gradle

push-image:
  stage: deploy
  script:
    - gradle build
      -Dquarkus.container-image.push=true
      -Dquarkus.container-image.group=${CI_PROJECT_NAMESPACE}
      -Dquarkus.container-image.name=${CI_PROJECT_NAME}
      -Dquarkus.container-image.registry=${CI_REGISTRY}
      -Dquarkus.container-image.username=${CI_REGISTRY_USER}
      -Dquarkus.container-image.password=${CI_REGISTRY_PASSWORD}
  cache:
    key: gradle
    paths:
      - .cache/gradle

sonarqube:
  stage: verify
  script: gradle sonarqube
