stages:
  - test
  - verify
  - deploy

image: gradle:7.3.3-jdk17

variables:
  SONAR_TOKEN: $SONAR_TOKEN
  GRADLE_USER_HOME: ".cache/gradle/"

cache:
  paths:
    - .cache

test:
  stage: test
  script:
    - gradle test

push-image:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_TAG'
  script:
    - if [ "$CI_COMMIT_TAG" ]; then IMAGE_TAG="$CI_COMMIT_TAG"; else IMAGE_TAG="latest"; fi
    - gradle build
      -Dquarkus.container-image.push=true
      -Dquarkus.container-image.group=${CI_PROJECT_NAMESPACE}
      -Dquarkus.container-image.name=${CI_PROJECT_NAME}
      -Dquarkus.container-image.tag=${IMAGE_TAG}
      -Dquarkus.container-image.registry=${CI_REGISTRY}
      -Dquarkus.container-image.username=${CI_REGISTRY_USER}
      -Dquarkus.container-image.password=${CI_REGISTRY_PASSWORD}

sonarqube:
  stage: verify
  script: gradle sonarqube
