stages:
  - build

image: gradle:jdk17

build:
  stage: build
  script:
    - gradle build
      -Dquarkus.container-image.push=true
      -Dquarkus.container-image.group=${CI_PROJECT_NAMESPACE}
      -Dquarkus.container-image.name=${CI_PROJECT_NAME}
      -Dquarkus.container-image.registry=${CI_REGISTRY}
      -Dquarkus.container-image.username=${CI_REGISTRY_USER}
      -Dquarkus.container-image.password=${CI_REGISTRY_PASSWORD}