// variables accessibles via {{var}}.
@hostname = 127.0.0.1
@port = 8080
@proto = http

@host = {{proto}}://{{hostname}}:{{port}}

// test_uuid of john doe user. First post will create
// this user, latter ones will create random uuids.
//@test_uuid = c044a099-e489-43f8-9499-c04a371dbb61
@test_uuid = 4eb0018f-6b14-4d4d-bbb0-8f5622a914fd

// using request variables we can get an access_token and store it.
// https://github.com/Huachao/vscode-restclient#request-variables
// get access token for alice user. (available by default in keycloak)
# @name auth_headers
curl -X POST http://localhost:8180/realms/quarkus/protocol/openid-connect/token     
--user backend:secret     
-H 'content-type: application/x-www-form-urlencoded'     
-d 'username=alice&password=alice&grant_type=password'

###
@access_token = {{auth_headers.response.body.$.access_token}}

###

# @name search_post
POST {{host}}/searches
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
    "query": "NOT ( hiv AND (json OR NOT lol) AND (bye OR dab) ) OR hello"
}

###
@search_uuid = {{search_post.response.body.$.uuid}}
###
@job_uuid = {{search_post.response.body.$.job_uuid}}

###
GET {{host}}/searches
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

###
# @name search_get
GET {{host}}/searches/{{search_uuid}}
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

###
@result_uuid = {{search_get.response.body.$.result_uuid}}

###
GET {{host}}/jobs/{{job_uuid}}
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

###
GET {{host}}/jobs
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

###
GET {{host}}/results
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

###
GET {{host}}/results/{{result_uuid}}
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

###
GET {{host}}/results/10
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json


###
GET {{host}}/results/{{result_uuid}}/articles
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json
