@hostname = 127.0.0.1
@port = 8080
@proto = http
@host = {{proto}}://{{hostname}}:{{port}}

###
GET {{host}}/users/138b5ce6-1cb2-47e0-ae10-97e61624a968
Content-Type: application/json
Accept: application/json

###
POST {{host}}/users
Content-Type: application/json
Accept: application/json

{
    "email": "bane@doe.org"
}

###
GET {{host}}/jobs
Content-Type: application/json
Accept: application/json

