@hostname = 127.0.0.1
@port = 8080
@proto = http
@host = {{proto}}://{{hostname}}:{{port}}

###
GET {{host}}/users/df5c040a-d5d0-4821-a6d1-4f75508ab97b/searches
Content-Type: application/json
Accept: application/json

###
POST {{host}}/users
Content-Type: application/json
Accept: application/json

{
    "username": "bane@johnson.co",
    "email": "bane@doe.org"
}
###
POST {{host}}/searches
Content-Type: application/json
Accept: application/json

{
    "query": "HIV AND AIDS",
    "user_uuid": "fe22d81a-547c-41fb-b53d-ef2afbd5bcc0"
}

###
GET {{host}}/searches
Content-Type: application/json
Accept: application/json

