// variables accessibles via {{var}}.
@hostname = 127.0.0.1
@port = 8080
@proto = http

@host = {{proto}}://{{hostname}}:{{port}}

// test_uuid of john doe user. First post will create
// this user, latter ones will create random uuids. 
//@test_uuid = c044a099-e489-43f8-9499-c04a371dbb61
@test_uuid = 4eb0018f-6b14-4d4d-bbb0-8f5622a914fd

###
GET {{host}}/users
Content-Type: application/json
Accept: application/json

###
POST {{host}}/users
Content-Type: application/json
Accept: application/json

{
    "uuid": "{{test_uuid}}",
    "username": "brody",
    "email":"brody@co.uk"
}

###
POST {{host}}/users/{{test_uuid}}/searches
Content-Type: application/json
Accept: application/json

{
    "user_uuid": "{{test_uuid}}",
    "query": "HIV OR NOT WUHAN"
}

###
GET {{host}}/users/{{test_uuid}}/searches
Content-Type: application/json
Accept: application/json

###
GET {{host}}/users/{{test_uuid}}/searches
Content-Type: application/json
Accept: application/json

@result_uuid=b17dd9ad-58d5-4a91-9aa6-4e364e351582
###
GET {{host}}/results/{{result_uuid}}/articles
Content-Type: application/json
Accept: application/json
